/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package JFRAME;
import java.sql.*;
import javax.swing.JOptionPane;
/**
 *
 * @author krish
 */
public class ReturnBook extends javax.swing.JFrame {

    /**
     * Creates new form IssueBook
     */
    public ReturnBook() {
        initComponents();
    }
public void UpdateCount()
{
    int BookId=Integer.parseInt("txt_bid.getText()");
    try
    {
        Connection con = DBCon.getConnection();
      String sql="update book_details set quantity = quantity-1  where BookId=?)";
         PreparedStatement ps=con.prepareStatement(sql);
         ps.setInt(1, BookId);
         int rowCount=ps.executeUpdate();
         if(rowCount>0){
             JOptionPane.showMessageDialog(this, "book updated");
         }
         else
         {
           JOptionPane.showMessageDialog(this, "can't update book count");
         }
    }
    catch(Exception e)
    {
        e.printStackTrace();
    }
}  
public void getIssueBookDetails()
{
    boolean sucess=false;
    int BookId=Integer.parseInt("txt_bid.getText()");
    int StudentId=Integer.parseInt("txt_sid.getText()");
        try
       {
           Connection con = DBCon.getConnection();
         String sql="select * from issue_book_details where BookId=?,StudentId=?and Status=?";
         PreparedStatement ps=con.prepareStatement(sql);
         ps.setInt( 1, BookId);
          ps.setInt(2, StudentId);
          ps.setString(3,"pending");
          ResultSet rs= ps.executeQuery();
         if(rs.next()){
             lbl_issueid.setText(rs.getString(Id));
             lbl_bname.setText(rs.getString(BookName));
             lbl_sname.setText(rs.getString(StudentName));
             lbl_issue.setText(rs.getString(Issue_Date));
             lbl_due.setText(rs.getString(rs.getString(Due_Date)));
             lbl_berror.setText("");
         }
         else
         {
           lbl_berror.setText("no record found");
           lbl_issueid.setText("");
             lbl_bname.setText("");
             lbl_sname.setText("");
             lbl_issue.setText("");
             lbl_due.setText("");
         }
       }
         catch(Exception e)
                 {
                 e.printStackTrace();
                 }
}
public boolean ReturnBook()
{
    boolean isreturn=false;
             int BookId=Integer.parseInt("txt_bid.getText()");
          int StudentId=Integer.parseInt("txt_sid.getText()");
 try
 {
      Connection con = DBCon.getConnection();
      String sql="update book_details set Status=? where BookId=?,StudentId=? and Status=?)";
         PreparedStatement ps=con.prepareStatement(sql);
         ps.setString(1,"returned");
         ps.setInt(2, BookId);
         ps.setInt(3, StudentId);
         ps.setString(4, "pending");
         int rowCount=ps.executeUpdate();
         if(rowCount>0){
             isreturn=true;
         }
         else
         {
           isreturn=false; 
         }
 }
 catch(Exception e)
 {
     e.printStackTrace();
 }
 return isreturn;
 }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        lbl_quan = new javax.swing.JLabel();
        lbl_id = new javax.swing.JLabel();
        lbl_name = new javax.swing.JLabel();
        lbl_aut = new javax.swing.JLabel();
        lbl_issue = new javax.swing.JLabel();
        lbl_bid = new javax.swing.JLabel();
        lbl_bname = new javax.swing.JLabel();
        lbl_sname = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        lbl_berror = new javax.swing.JLabel();
        lbl_due = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txt_id = new app.bolivia.swing.JCTextField();
        txt_id1 = new app.bolivia.swing.JCTextField();
        rSMaterialButtonCircle1 = new rojerusan.RSMaterialButtonCircle();
        jLabel24 = new javax.swing.JLabel();
        rSMaterialButtonCircle2 = new rojerusan.RSMaterialButtonCircle();
        jPanel7 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(255, 51, 51));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/AddNewBookIcons/icons8_Literature_100px_1.png"))); // NOI18N
        jLabel12.setText("Book Details");
        jPanel5.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, -1, -1));

        lbl_quan.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lbl_quan.setForeground(new java.awt.Color(255, 255, 255));
        lbl_quan.setText("Issue Date:");
        jPanel5.add(lbl_quan, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 460, 100, 30));

        lbl_id.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lbl_id.setForeground(new java.awt.Color(255, 255, 255));
        lbl_id.setText("Book Id:");
        jPanel5.add(lbl_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 100, 30));

        lbl_name.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lbl_name.setForeground(new java.awt.Color(255, 255, 255));
        lbl_name.setText("Book Name:");
        jPanel5.add(lbl_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 130, 30));

        lbl_aut.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lbl_aut.setForeground(new java.awt.Color(255, 255, 255));
        lbl_aut.setText("StudentName:");
        jPanel5.add(lbl_aut, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, 100, 30));
        jPanel5.add(lbl_issue, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 460, 160, 30));
        jPanel5.add(lbl_bid, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 260, 160, 30));
        jPanel5.add(lbl_bname, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 330, 160, 30));
        jPanel5.add(lbl_sname, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 390, 160, 30));

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 280, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        jPanel5.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 280, -1));
        jPanel5.add(lbl_berror, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 570, 300, 40));
        jPanel5.add(lbl_due, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 530, 200, 30));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Due Date:");
        jPanel5.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 530, -1, -1));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 10, 420, 810));

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 280, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 200, 280, -1));

        jLabel21.setBackground(new java.awt.Color(255, 255, 255));
        jLabel21.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 51, 51));
        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/AddNewBookIcons/icons8_Books_52px_1.png"))); // NOI18N
        jLabel21.setText("Return Book");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(1450, 160, -1, -1));

        jLabel22.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel22.setText("Book Id:");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(1440, 260, -1, -1));

        txt_id.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 51, 51)));
        txt_id.setPlaceholder("Enter Book Id");
        txt_id.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_idFocusLost(evt);
            }
        });
        txt_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_idActionPerformed(evt);
            }
        });
        jPanel1.add(txt_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(1560, 250, -1, -1));

        txt_id1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 51, 51)));
        txt_id1.setPlaceholder("Enter Student Id");
        txt_id1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_id1FocusLost(evt);
            }
        });
        txt_id1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_id1ActionPerformed(evt);
            }
        });
        jPanel1.add(txt_id1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1560, 320, -1, -1));

        rSMaterialButtonCircle1.setBackground(new java.awt.Color(255, 51, 51));
        rSMaterialButtonCircle1.setText("Return");
        rSMaterialButtonCircle1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonCircle1ActionPerformed(evt);
            }
        });
        jPanel1.add(rSMaterialButtonCircle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1400, 450, 390, 70));

        jLabel24.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel24.setText("Student Id:");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(1420, 330, -1, -1));

        rSMaterialButtonCircle2.setBackground(new java.awt.Color(255, 51, 51));
        rSMaterialButtonCircle2.setText("Find");
        rSMaterialButtonCircle2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonCircle2ActionPerformed(evt);
            }
        });
        jPanel1.add(rSMaterialButtonCircle2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1400, 370, 390, 70));

        jPanel7.setBackground(new java.awt.Color(255, 0, 51));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 280, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1440, 210, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons/library-2.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 980, 690));

        jPanel6.setBackground(new java.awt.Color(255, 0, 0));

        jLabel11.setBackground(new java.awt.Color(0, 0, 255));
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/AddNewBookIcons/icons8_Rewind_48px.png"))); // NOI18N
        jLabel11.setText("Back");
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel11)
                .addGap(0, 2, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 0, 1840, 803));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        HomePage page =new HomePage();
        page.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel11MouseClicked

    private void txt_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_idActionPerformed

    }//GEN-LAST:event_txt_idActionPerformed

    private void txt_id1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_id1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_id1ActionPerformed

    private void rSMaterialButtonCircle1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonCircle1ActionPerformed
        if(ReturnBook() == true)
{
     JOptionPane.showMessageDialog(this, "book returned sucessfully");
UpdateCount();
}
else
{
     JOptionPane.showMessageDialog(this, "book returned failed");
}
 
    }//GEN-LAST:event_rSMaterialButtonCircle1ActionPerformed

    private void txt_idFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_idFocusLost
     
    }//GEN-LAST:event_txt_idFocusLost

    private void txt_id1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_id1FocusLost
 
    }//GEN-LAST:event_txt_id1FocusLost

    private void rSMaterialButtonCircle2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonCircle2ActionPerformed
getIssueBookDetails();      
    }//GEN-LAST:event_rSMaterialButtonCircle2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReturnBook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JLabel lbl_aut;
    private javax.swing.JLabel lbl_berror;
    private javax.swing.JLabel lbl_bid;
    private javax.swing.JLabel lbl_bname;
    private javax.swing.JLabel lbl_due;
    private javax.swing.JLabel lbl_id;
    private javax.swing.JLabel lbl_issue;
    private javax.swing.JLabel lbl_name;
    private javax.swing.JLabel lbl_quan;
    private javax.swing.JLabel lbl_sname;
    private rojerusan.RSMaterialButtonCircle rSMaterialButtonCircle1;
    private rojerusan.RSMaterialButtonCircle rSMaterialButtonCircle2;
    private app.bolivia.swing.JCTextField txt_id;
    private app.bolivia.swing.JCTextField txt_id1;
    // End of variables declaration//GEN-END:variables
}
